language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
before_install:
- export TZ=Pacific/Noumea
env:
  global:
  - secure: rr4LXc4MldkytHKuniIJoqX7Ap084CWl6a7SEfiN/cDZlt9NDxO2L2+MIe90TRI8UHKv6eqt0sOHUHRSQlJMygyzZl4Z1rqzHgcCdhuYuQgWQO1VV2mZ2oSYOMfckkYHcb+fHyYiF0/m9xQjoIGX+2JuqLUbyKme68dHqXReDtSk8tjJ3Iiz9gDZzDgT/qN3ifq9o/F4iQJkThTg89IUS7+eDHCgM7LWrcgen0kmwr7ViQbU+t6M3BmNzCmhjk8KG1eOMIJOIbN60xPVXU25qZIp/XAZ2uBkLcahrdtMu6xF+yFbfoFGTY3dXiWXeLYQ1iaH3zboluh7pOfkHI3wHm7hOYMRQerROjPHLoTMcNp1AAltnfUQz52PSZOyRv17kIG7YeOcHpIo4mBuARfWuj8jwxyN822ptRBgJarBhnyA5nfEV6LvvDE9e6M72dAEbwpHxwsaTkVG4YY8Uws+UH/1CvzXq/9kH7pNFjjgFcfik9qA+jL+MNusYRddnGZwU26auR5RRfFCMjxAXrjxtXcYhRTUtAqnsczl0FWIqYKqWuWCYGFk9qwz7hh9Fq4PGTUMXLGrHVHqk4eudYGabldziQ7Qh3Mj1ktbQuQbPY0OZzqgtrJAvcq1Wp8QSg6792uMxbPdyxBuk8WqMmtY7ZKbYq3rns9IAzuR26Y0jEM=
  - secure: CQjg1qNyi31c++LfIfdXSUrEhBeqXcvusHdMfxtKjKOwP7V3ei03E7yIi+BCQAVI+K3F2Od+m1Qt02avKpfA4JbHLKG/FnMaNO25qwe70UsMPw4oj+7w8KOmfRElPWUhJ0go6/kihjeqviJWVNG5nSYU+NrSYZsvW4tStUXoWrRo5j6kZ41DNp+peck8mQWYoaQYPa9FqhqfEBkUdEXhkz5oH/rRexNQpIdHlyXRrIgFywBAYkkbk/V09gUE0VZuXyC5JCmIqMP0bg3UQ2YjV2aNyN7DCO++GWscZ4CrpyRO+mBY3n6dVqOUDICQsEX+X42Ct6zo4Nj+GE6iDlJ4z7cQtYnPk5q2M9h7PuunEkWH69KMBkf9XuM9S5w/lRhiQ5HSKTusULhOkZZA4somCS2REFMXGPUgnKFaBCLOZsBAhSxRzKT08FZ1XCf5+oQXxhNDv/l0JxzESR/wz9opWWnAyKVQ2XrShVZvdwltE72ZKmqjnbLazLHfTDhf1a53wmCfpDjmxMD8y32ZN1DfP0w80t+iaDzSjr4S8bT9nqzP1IKAQvG3VthD1yduk1Y3gxP+YauzWCJNMcOplh4Liq4K6vz9TJyLroK1/jWq0nYCVCtLTFOHyDboggyYK05CnkBgHdQLToB3LF+qYq0DWEVVLizkSq8b9n6s7MRdPOg=
  - secure: X+sVNvJluVPeBRKsNr8mXVTSngFKk6qmHV/+Fi956X53pWW9dWJOZZpIsfZ4wcwcU7CQeAxD5JsYhWTTwhuUf/kZyHGAOh+nzf3ooHzgkGmPY9zFiTQjm9Lb5NJJVK+IQGw7RFYD5QPDvh9LfbG5QQ6hEDz8uHif3Eo/UCHeUcyoX3A3iLmlx71ykH9BDNtWAR8Q3uhdAy42DPAUHkyFWEfhiDZDH4VrRx8M+gS70+tT1XsH8BD86/RUkPJ1tfkxb3Gnm/oXYW9xLK9fnwiSreGQPGfRCrtEruUNTk5l/kGLtc9ZDX6JlcbU9MuYxByb/3fpKbpFs+daO7BY+vUZtExVvdizJ2gfos3R4AtfVLlM0Qq3CkWSHyc9XArpO56zuzO1rs4QNU+OmbHQDtOy9j29QgaZKB3OKSzap2edNzTeF8OeubRsWpr0dtLMF1YgyRyEGB9aOwWXYfhYQZEA4NfiQ3CdjW5VZmwhLxrR7t/HbCZVipx4m9wzLa99hBGlaLhP/bLu+GEFTvHzWeVd77P9Z6KM9hcdTXRoGG6510fmxkQ0VYKmKBBabOjrc3hASETaZJ4GWcoYhfrXwMBj6cJmEXxNqwsiovfpZ3Cpwd02/DExVscVAT1QToIs2qMbRx38ZCLVfdAiR4CEVOeVoEMsGza3uxwYvF5ctgxR03s=
script:
- mvn versioneye:update test jacoco:report
after_success:
- mvn coveralls:report
before_deploy:
- export RELEASE_PKG_FILE=$(ls target/*.war)
- export RELEASE_PKG_MD5_FILE=$(ls target/*.war.md5)
- export RELEASE_PKG_SHA_FILE=$(ls target/*.war.sha1)
- echo "deploying $RELEASE_PKG_FILE , $RELEASE_PKG_MD5_FILE , $RELEASE_PKG_SHA_FILE to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: TwzQHlKR62mJdc7Jyy7ZE869K/7Rxnc/YRYPO4DnReN8wZvYHS+xWoPDBD3gDTihAO3dYbFOee3zNeAsXcv9ALI/Pm0ff01FsWytjc37Y2+13FQevlhutQ8YQi5+OXF6nYSFmKNtwwvpM18GhtDGtT/HAcB66/+ugKyhYLTSQ4BSKj+RjIIo9/wcO9YsLzYqnUwnrPpehNULBwI+rG7byLUqE2UW00Gy6XPmOFHM89zYVvzsaJlZ4gI8vAx9lDZS7qBWpTp85/9VkutpgsULphPYBgfAqKv+kQ6YiV4j1dEIxJncfG/QN3RGUeEObG9kcw8XItRdtpMoUMdHsnH0MjtCWhnbJNQrgbOTlJuc2nqCFqE9B6wrUCKdwmsnlWhRYHc2llqnxpxU5Mh5XndnE3UskLjnFE4cDEaeJtqlKQuzXxhVfFnxQddjPU78d3iPww3uFjmHm32Y1OGwyh48H+1dJpkEXiBDmIXrBImSC3v4+yOeDp5Mu3HWnFUzX9CNcdr50SXKAOxWqRMABrjZZOVBhbvk/Ap16STfYR1x3Lzz1OTLLHSmnqUo6CXBEjZbfMNka1+QVkWhKVU/d6AovP1slIk55WQLDAji72ZefaUIZPeDaahzsx5HDRnmDoypSN/0YoX8m5z7dHXx75OoLZTRn1S/4k8H7IcNl2plenI=
  file: 
  - ${RELEASE_PKG_FILE}
  - ${RELEASE_PKG_MD5_FILE}
  - ${RELEASE_PKG_SHA_FILE}
  skip_cleanup: true
  on:
    tags: true
    repo: DSI-Ville-Noumea/sirh-jobs
notifications:
  slack:
    secure: E5vkBwd+3c9tCnGbhz2XgbOINuJCmGxz2FlLJghPGqmhFQSZHkqaKrvcOCEkQiIIJ6Y2A1PiTE1rccfsZ2oUWHWbtP+Bt1+iviyAcxx/zEudj/N6fwFlqkqKQ46hvAkyVyptaOHn7ZBzEwG41iZxnVOHQ0iCfNwrwdrEIvq2FYFPOw3jemU4UOyHX0tvi1OkcTsilHRP2ndaq20ZZ4fgENNgp2jo8h7lAfPKPgrsy4MZJbUGiXw3F4JJsEOw5Bqa17ldaRJQtw8DEqmkdsGqqsCbM+HKC78Rveq5qO3vAEec8gKZblgyEAJl4U23FufOohlKzGARel6u7ivbIuovFMYJQLy/NqX82oT8q82XW14nAOnhzlvdlxblTT1Bn9S38mNwQCV+Y7q21nZif3/0A77C5B+rYjge2A4xS61I7YrjlvG491zsXy5RGrW/muHCxTVOju93p/fQhk6d8ANTQYt51yZ5Bogo+wARiVKKLR3skBPK+FVC3QCHqlUXv1RdaGb05ORlmPBkhR162zSouox1ZPOsmbiRHYvia4+3dNDGzLKj1+Qne+vvpp0iw/K7kCCTXFLwOTD90Eda+Us9T5x0RHdSODAKDXX8sb6dxDcAMG1Sq6KjecTHpwFcORYlfGORmBBHsMtF6HpdKVmVhMiadrqwY92kCIK4ghXF8bI=
