language: java
sudo: required
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
before_install:
- export TZ=Pacific/Noumea
install: mvn install -DSkipTests=true -Dmaven.javadoc.skip=true -DcreateChecksum=true
env:
  global:
  - secure: vZshNf7gyH7NXibuZY2n+fbDX7mm0NYq07Y5VcqyPM28IggNG3xGkEUPIxsROe/SJXCTfb1yKTue1Moxidql7JA4rodP7t/mdUaSYRtUnr4JtmqFWTLGbb7X2JwlKStJ1Dcm7oJ16EVoYgfE9e93TXRpRouuUbmDEih99PKN8OKxbucp5zSsqqBN24TVzmvyw5Tf914yVHn23Y4lFQgD0oX9vE/CjO+GxzxSwzosJs4acIDGJFmL3Ex1oAlDDokdDtBLEGQVKNWg0jRMNReZqvov2i+d6Sf67KBeth9NWIuTBQdP1d0SAnFn9oNXYsch3iW7iHZxi2+5D3RSDeCPhBGGWgL2ZLGAUeYxtoIFF2n3HMU7CMP7JN3R+r11drOqmJRzx0Zxsqp86cTuKcI92YTWi+hiqcpL/QU5GJx5I9S2zhHx+6OEPOkNdUgwsnSrSgkNgeXqs5XJCV5KgJFBYVsItsFjPQrXXIazbPMR6Z2oP11pgjUmxm6/oekJhnArtCpYcZm22rY153Qxbm9nWe3sH/nJnJaMLGtIctd2z/IbguxpiMGwlA7RMkJfAMMeySYoPe5BB9AX0eJxrEu2SwBBCGsa9kWh1nmY9VhaDUZ7U4XOAUds8A9fUHMmcW4QxvCRDSlvHsLEzRoyZ9o54Sr1PIhkrtCXKIqFcqxaeYc=
script:
- mvn test jacoco:report
after_success:
- mvn coveralls:report
before_deploy:
- export RELEASE_PKG_FILE=$(ls target/*.war)
- export RELEASE_PKG_MD5_FILE=$(ls target/*.war.md5)
- export RELEASE_PKG_SHA_FILE=$(ls target/*.war.sha1)
- echo "deploying $RELEASE_PKG_FILE , $RELEASE_PKG_MD5_FILE , $RELEASE_PKG_SHA_FILE
  to GitHub releases"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: xElF7dCNsHP6ObhHOTcjScrFrBtvkcuYR4xDIF8OflELMBgtxeK7hi1j9TJMJm2VHQZJVBFjaqLSn8D2Odrs+mL9vjIgCsDdOLLBJEaEe78kfgLfsmhNY0eNj2RZqlfXe3k4T86ALOynskBzQP98yfE1lcGZaj+tXlyVAJ8GVSZIhpQKtHBg2a3Kz1RXkUhnhpl37LErVl4idwPEAvo2M3hZ0XBPEiZ0Y9IHXU9T0XYjZFF6ZviSs1sJlLC/Elo4fQBqBDjQKHWIpnf/668bNNe00y6lWRKkADZFnVAVZxImbThst5L7HIqoRsrpgF6isshWlphxb8JTCoaATxTYVsA6ASZqN0t/OLaVFDYhrQK14kNj2KIoLOKB08YyuUhASnl465c+OJy/xOytv+LHYne7h4WJjb9Bx/40QvrrlxIZcPe/FiCKUN0x+bv+LTjgvHiohHG8xjJ0CNEMUG44+SFPSmCGmJ1Uu48jCeSDPa7NOMQhwKqe4zV4f6AWTdAqCoXwGLnofkER/BgZ7f9BKnHgrQT5pbSj1PkG20usqLsUmF+rs1ekV5q/TGlE9xWJKFv39D+x3Kn7k6Z2O+xDY5wBShfNXB598ydo+fqXTpVAmWkpAQv/sCuNejGZveXXtSZlGSuoA3apIfaYKoYwMYTP6VlbfdR81j0hKRvcrPs=
  file:
  - ${RELEASE_PKG_FILE}
  - ${RELEASE_PKG_MD5_FILE}
  - ${RELEASE_PKG_SHA_FILE}
  on:
    tags: true
    repo: DSI-Ville-Noumea/sirh-jobs
notifications:
  slack:
    secure: eW0NHYV58mZMWziLNlp5yt2C62Y+PO06o0jCqbPDfBnl02ZyYBwgoKnqPDFOFyQAGpYMmoUcEULZ8rkEB7JMjDQwOp0iEHhtIce07sOdobuGhHLq6+HwArN7+SX3uE/qHKN8o1iPcr1JNGcliUzIWvjrM3WI9FS4MYR4wHyly17Bge8zV2aT9H5Vwfqox/JLP8grri9vLdfbv1KZHgRXSNLWxWWK1GJzyEDcZEkmRT/p7zE843HUL5TM8HWHJilhF5YECNwSdRYfJct/aI4xmohbDxoOfE3MIq2laz5PAFV4EiFcaBQcRnOjlIhMTNJ8sZvXxIPZI+zEQ045GMOq03Bg6xpt4hrf0zfzsOX2p3FjH5/cpmflQ5SdRWrI5nOVBrBccDIqdyoWDD15ODrqt9GBdQaQJ4ZdYxqgph+GEGsIARnXKITHw02h0LytyBY9BWaZSRrIRERK942rb+YnMf3Uo0W+R0HONixiDCsmLhs9GspdFzsLEBFF7CEw7m5SQHDsWnUAec1oa6Au1mOcSgz8VubfzTp6kAm8vmPvgI19XLOKxEiQ487XzOij0mD1XnwXA8xCGYTcC/LtTlAX90atznneCSc1ObnCXGMtZ9Rt3TwCHeKaBhPc+OLFwJk2IQEA0jZYCSe6NNTtxf+bS4avkaKWsBN1dxm6LlKqB2s=
